version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - REPO_PATH=${REPO_PATH}
    env_file:
      - .env
    volumes:
      - .:/app
      - ${REPO_PATH}:${REPO_PATH}
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "fastapi_app:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    networks:
      - git-autobot-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - git-autobot-network

networks:
  git-autobot-network:
    driver: bridge
