[project]
name = "git-autobot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gitpython>=3.1.44",
    "pygithub>=2.6.1",
    "typer[all]>=0.12.3",
]

[project.scripts]
git-autobot = "git_autobot.__main__:app"
